echo Đang hoàn tất thiết lập cho Fansub Edition...
echo ..........................
echo Đang hoàn thành...
echo ..........................
echo Đã xong! Tốc độ thiết lập là 3.2 giây
echo ..........................
sudo apt update &>/dev/null 
sudo apt install aegisub handbrake transmission -y &>/dev/null 
sudo apt install gnome -y &>/dev/null 
sudo apt full-upgrade -y &>/dev/null 

